name: Publish Docker image to Docker Hub

on:
  release:
    types: [created]

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build Docker image
        run: |
          make build-docker TAG="${GITHUB_REF_NAME#v}"
      - name: Publish Docker image
        run: |
          make push-docker TAG="${GITHUB_REF_NAME#v}"
      - name: Tag latest Docker image
        run: |
          make push-docker-latest TAG="${GITHUB_REF_NAME#v}"
