name: Test Docker image

on:
  push:
    branches: [ main ]
    paths-ignore:
      - 'docs/**'
      - CHANGELOG.md
      - LICENSE
      - README.md
  pull_request:
    branches: [ main ]
    paths-ignore:
      - 'docs/**'
      - CHANGELOG.md
      - LICENSE
      - README.md

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Install Goss
        run: curl -fsSL https://goss.rocks/install | sh

      - name: Run tests
        run: make test-docker
