name: Run tests

on:
  push:
    branches: [ main ]
    paths-ignore:
      - 'docs/**'
      - CHANGELOG.md
      - LICENSE
      - README.md
  pull_request:
    branches: [ main ]
    paths-ignore:
      - 'docs/**'
      - CHANGELOG.md
      - LICENSE
      - README.md

jobs:
  test:
    name: Tests
    strategy:
      fail-fast: false
      matrix:
        include:
          - php: '8.1'
          - php: '8.2'

    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 2

      - name: Setup PHP with Composer
        uses: shivammathur/setup-php@v2
        with:
          php-version: "${{ matrix.php }}"
          tools: composer
          ini-values: phar.readonly=Off

      - name: Install dependencies
        run: composer install

      - name: Run tests
        run: ./vendor/bin/phpunit --display-warnings
